### ISSUE TITLE
hey loved your blog post Accessing Go from Julia but

### ISSUE THREAD

**Issue by AbhimanyuAryan** [rsdoiel/rsdoiel.github.io#3]
I am trying to replicate this example on my macbook m1 and running into problems. I am not familiar with Go and just started learning it. Can you please take a look

```
GoByExample.jl/GoJsonJulia on  master via C v14.0.0-clang via 🐹 v1.19.2 via ஃ v1.8.2
❯ julia libjsonpretty_test.jl
ERROR: LoadError: ArgumentError: Package libjsonpretty not found in current path, maybe you meant `import/using .libjsonpretty`.
- Otherwise, run `import Pkg; Pkg.add("libjsonpretty")` to install the libjsonpretty package.
Stacktrace:
 [1] macro expansion
   @ ./loading.jl:1163 [inlined]
 [2] macro expansion
   @ ./lock.jl:223 [inlined]
 [3] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1144
in expression starting at /Users/abhi/Git/GoByExample.jl/GoJsonJulia/libjsonpretty_test.jl:2
```

code: https://github.com/AbhimanyuAryan/GoByExample.jl/tree/master/GoJsonJulia

**Comment by rsdoiel** [comment]
Debugging cross language stuff is challenging. For me almost all the problems are around either a bad assumption I've made (likely) or something subtle in my code (e.g. objects destroyed in Go before they pass to Julia). 

So here's how I think things should work in Julia to use shared libraries. I think what Julia needs to do a few things.

1. Find the shared library in question (<---- This is what your error message is about )
2. Load the library and map into Julia run time and the shared library
3. Use the share library as appropriate (things worked if you got this far)

If you make it to step three you will have two independently managed memory spaces. One in the Go thread controlled by Go's run time and the other in the Julia thread for Julia things. The library function calls are how you share data between them.  

I've looked at your repositories and nothing jumps out as a problem. The line in libjsonpretty.jl 

```
value = ccall((:jsonpretty, "./libjsonpretty"), Cstring, (Cstring,), txt)
```

I'm pretty sure is where Julia stops being happy. It's  not finding "./libjsonpretty" in your library search path in the path that it searches. This makes me think the problem is in our assumption about how Julia searches to find the library on macOS on M1.

I doing a bit of internet searching I found this post (last on page) which maybe helpful.

    https://discourse.julialang.org/t/how-to-add-shared-c-library-to-the-load-path/31061/3

I think the last entry is where I would start looking to find a solution.  

```
There are basically 3 cases to consider:

    The library is already in a standard load path. No problem to solve.

    The library is provided with or downloaded value = ccall((:jsonpretty, "./libjsonpretty"), Cstring, (Cstring,), txt)by your Julia code. Then you know its position relative to the file using it and can easily compute the direct path with the help of abspath and @__DIR__.

    The library is available in a non-standard location unrelated to the location of your Julia code. In this case you have to do something to inform Julia where it is. One option is to add it to the library load path. Another to set a separate environment variable that your Julia code reads to construct a direct path (environment variables are available in the ENV dict).

In case 2 there is no discussion that constructing a direct path is clearly better than modifying the library load path. If you look at packages wrapping external libraries, that’s what they do.

In case 3 it’s more of a draw. If there are other benefits of having it in the library load path, that’s obviously the way to go. If not it’s about the same complexity to set e.g. LD_LIBRARY_PATH as to set a custom environment variable. Except you might make a mistake when you set LD_LIBRARY_PATH and overwrite what was there before, which turned out to be something you also needed.
```

I would try explicitly using the full path and see if that changes the out come. The second think would be to put the shared library in a standard location that macOS expects. Note I've recently had issues "copying" a binary and macOS's security efforts. If I compile a Go program and any to install it into /usr/local/bin I have to move it (i.e. use the "mv" Unix command, not "cp"). I don't know if this security is part of the reason the library search path isn't picking up your "./" file path reference.  I don't have this problem on other operating systems I use at work. It's a macOS thing.

Hope this is helpful and sorry I didn't have an easy fix.

**Comment by rsdoiel** [comment]
Quick addition, I looked at https://docs.julialang.org/en/v1/manual/environment-variables/ and notice there is a Julia environment variable for load path. I assume this is Julia modules but that may be helpful to try as well.

**Comment by AbhimanyuAryan** [comment]
Sure no worries I will take a look at this on weekend

**Comment by AbhimanyuAryan** [comment]
Thanks a lot for these debugging instructions
